# Generated by Django 3.2.5 on 2021-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dis',
            field=models.TextField(default='product'),
        ),
        migrations.AlterField(
            model_name='catergory',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
